{
 "title": "ML service dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ModelType", "query": "lr, cb" },
   { "name": "Gender", "query": "f,m" }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'Error rate')",
     "targetFull": "alias(divideSeries(aliasByNode(movingAverage(stats.ml_service.predict_gender.request_status.error.count, '1min'), -2), movingAverage(sumSeries(stats.ml_service.predict_gender.request_status.*.count), '1min')), 'Error rate')"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.ml_service.predict_gender.request_status.success.count"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Success Error Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "aliasByNode(stats.ml_service.predict_gender.request_status.*.count, 4, -1)"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'Error rate')",
     "targetFull": "alias(divideSeries(aliasByNode(movingAverage(stats.ml_service.predict_gender.request_status.error.count, '1min'), -2), movingAverage(sumSeries(stats.ml_service.predict_gender.request_status.*.count), '1min')), 'Error rate')"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'Error rate')",
     "targetFull": "alias(divideSeries(aliasByNode(movingAverage(stats.ml_service.predict_gender.request_status.success.count, '1min'), -2), movingAverage(sumSeries(stats.ml_service.predict_gender.request_status.*.count), '1min')), 'Error rate')"
    }
   ]
  },
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Feature Extraction Timing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(scale(stats.timers.ml_service.predict_gender.$ModelType.timing.feature_extraction.upper_90, 1000), -4, -2)"
    }
   ]
  },
  {
   "title": "Mean Feature Extraction Timing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(scale(stats.timers.ml_service.predict_gender.$ModelType.timing.feature_extraction.mean, 1000), -4, -2)"
    }
   ]
  },
  {
   "title": "Std Feature Extraction Timing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(scale(stats.timers.ml_service.predict_gender.$ModelType.timing.feature_extraction.std, 1000), -4, -2)"
    }
   ]
  },
  { "title": "Probas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Probas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.ml_service.predict_gender.$ModelType.result.$Gender.proba, -4, -2)"
    }
   ]
  }
 ]
}